export const strings = {
  // ** register page
  firstNameLabel: "First name",
  firstNamePh: "Enter first name",
  lastNameLabel: "Last name",
  lastNamePh: "Enter Last name",
  emailLabel: "Email",
  emailPh: "Enter email",
  emailReq: "Enter email",
  emailInvalidMsg: "Please enter valid email",
  passLabel: "Password",
  passLabelPh: "Enter password",
  passLabelReq: "Password is requierd",
  passwordMust:
    "Password must be at least 8 characters, 1 uppercase, 1 lowercase & 1 number",
  confirmPassLabel: "Confirm password",
  confirmPassLabelPh: "Enter confirm password",
  confirmPassLabelReq: "Confirm password is requierd",
  confirmPassVali: "Password & confirm password must be same",
  orgNameLabel: "Organization name",
  orgNamePh: "Enter organization name",
  orgNameReq: "Please enter organization name",
  orgAddressLabel: "Organization address",
  orgAddressPh: "Enter organization address",
  orgAddressReq: "Please enter organization address",
  orgDropdownLabel: "Organization employees size",
  countryLable: "Select your country",
  orgSizeLable: "Select organization size",
  createUserSuccess: "User created successfully",
  createUserError: "Error while creating user",
  loginSuccess: "User login successfully",
  loginError: "Error while user login",
  geoLocationError: "Error while fetch geolocation",
};
